### ISSUE TITLE
Activation e-mail: registering with an e-mail that does not exist

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/wn-user-plugin#46]
Users can register with e-mailadresses that don't exist.

For example:
I register using email@hotmail.co**l**.
I get a green flash message saying an activation e-mail has been sent to the e-mailadress.

In my case, a guest account is created using that invalid e-mailadress.

Possible solution:
The green flash message shouldn't appear.
Since the e-mail failed, a red flash message should appear saying that the e-mailadress does not exist. A user should not be created.

**Comment by mjauvin** [comment]
But you won't know if the email address is valid or not, so there's no way around this.

**Comment by mjauvin** [comment]
If you want to be sure the email exists, just require a confirmation code for the email, which can only be obtained if the email was received...

**Comment by bennothommo** [comment]
There's no way that we can determine that an email address truly exists. It is up to the user to ensure they're using the correct email address.

Using "user" activation, as @mjauvin suggested, is the best way to mitigate this as they'll need to approve the registration via an email in their inbox, which they obviously won't get if they've used an incorrect email address.

**Comment by AIC-BV** [comment]
If this fails in a try catch, you know the e-mail couldn't be delivered, thus the e-mail is invalid?
https://github.com/wintercms/wn-user-plugin/blob/main/components/Account.php#L324

**Comment by mjauvin** [comment]
A non existent email is one thing, misspelling an email that ends up being someone else's email is another...

**Comment by mjauvin** [comment]
Also, not all mail servers will tell you right away an email does not exist.

**Comment by bennothommo** [comment]
@AIC-BV that's two separate issues - putting a try/catch would pick up that the mail couldn't be delivered because of a failure to actually *send* the email (ie. the configured mail server failed). But given that this would be logged, I don't think we need to double-handle this.

As for your service that determines if the email address doesn't exist, yes, they would be relying on waiting for a bounce-back from the recipient's mail server, but as @mjauvin mentioned, there's no garuntee a bounce-back will be sent, and any functionality to this effect would require a connection to a mail inbox through IMAP/POP3 which is overkill IMO for this scenario.
