### ISSUE TITLE
Will rainLab-userplus be forked here as a winter cms plugin?

### ISSUE THREAD

**Issue by ideepblue** [wintercms/wn-user-plugin#9]
I have several projects that rely on the user plus plugin. I found the rainlab user, location, and notify plugins had been forked. But the rainlab user plus plugin is not here. Will you do that?

**Comment by LukeTowers** [comment]
Personally I've always thought of it more as an example of what you can do with your own plugins rather than something that should be relied upon in production, so I wasn't interested in forking it, but it seems like there is a large amount of developers requiring it in their projects so I guess we probably should. @mjauvin can you take care of forking it & rebranding / replacing it?

**Comment by mjauvin** [comment]
I'll get right on it!

**Comment by mjauvin** [comment]
https://github.com/wintercms/wn-userplus-plugin
